# Generated by Django 4.2.7 on 2023-12-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping_method',
            field=models.CharField(default='standard', max_length=20),
        ),
    ]
