# Generated by Django 4.2.7 on 2023-12-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orders_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_option',
            field=models.CharField(default='standard', max_length=20),
        ),
    ]
